// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: service.proto

package servicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SampleService_UnaryCall_FullMethodName                   = "/servicepb.SampleService/UnaryCall"
	SampleService_ServerToClientStreamingCall_FullMethodName = "/servicepb.SampleService/ServerToClientStreamingCall"
)

// SampleServiceClient is the client API for SampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleServiceClient interface {
	UnaryCall(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
	ServerToClientStreamingCall(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (SampleService_ServerToClientStreamingCallClient, error)
}

type sampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleServiceClient(cc grpc.ClientConnInterface) SampleServiceClient {
	return &sampleServiceClient{cc}
}

func (c *sampleServiceClient) UnaryCall(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, SampleService_UnaryCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleServiceClient) ServerToClientStreamingCall(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (SampleService_ServerToClientStreamingCallClient, error) {
	stream, err := c.cc.NewStream(ctx, &SampleService_ServiceDesc.Streams[0], SampleService_ServerToClientStreamingCall_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sampleServiceServerToClientStreamingCallClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SampleService_ServerToClientStreamingCallClient interface {
	Recv() (*ResponseMessage, error)
	grpc.ClientStream
}

type sampleServiceServerToClientStreamingCallClient struct {
	grpc.ClientStream
}

func (x *sampleServiceServerToClientStreamingCallClient) Recv() (*ResponseMessage, error) {
	m := new(ResponseMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SampleServiceServer is the server API for SampleService service.
// All implementations must embed UnimplementedSampleServiceServer
// for forward compatibility
type SampleServiceServer interface {
	UnaryCall(context.Context, *RequestMessage) (*ResponseMessage, error)
	ServerToClientStreamingCall(*RequestMessage, SampleService_ServerToClientStreamingCallServer) error
	mustEmbedUnimplementedSampleServiceServer()
}

// UnimplementedSampleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSampleServiceServer struct {
}

func (UnimplementedSampleServiceServer) UnaryCall(context.Context, *RequestMessage) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryCall not implemented")
}
func (UnimplementedSampleServiceServer) ServerToClientStreamingCall(*RequestMessage, SampleService_ServerToClientStreamingCallServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerToClientStreamingCall not implemented")
}
func (UnimplementedSampleServiceServer) mustEmbedUnimplementedSampleServiceServer() {}

// UnsafeSampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleServiceServer will
// result in compilation errors.
type UnsafeSampleServiceServer interface {
	mustEmbedUnimplementedSampleServiceServer()
}

func RegisterSampleServiceServer(s grpc.ServiceRegistrar, srv SampleServiceServer) {
	s.RegisterService(&SampleService_ServiceDesc, srv)
}

func _SampleService_UnaryCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).UnaryCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SampleService_UnaryCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).UnaryCall(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleService_ServerToClientStreamingCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SampleServiceServer).ServerToClientStreamingCall(m, &sampleServiceServerToClientStreamingCallServer{stream})
}

type SampleService_ServerToClientStreamingCallServer interface {
	Send(*ResponseMessage) error
	grpc.ServerStream
}

type sampleServiceServerToClientStreamingCallServer struct {
	grpc.ServerStream
}

func (x *sampleServiceServerToClientStreamingCallServer) Send(m *ResponseMessage) error {
	return x.ServerStream.SendMsg(m)
}

// SampleService_ServiceDesc is the grpc.ServiceDesc for SampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.SampleService",
	HandlerType: (*SampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryCall",
			Handler:    _SampleService_UnaryCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerToClientStreamingCall",
			Handler:       _SampleService_ServerToClientStreamingCall_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
